version: '3'

services:

    nginx:
        container_name: nginx
          #image: nginx:1.21
        build:
          context: .
          dockerfile: ./nginx.dockerfile
        ports:
            - "8095:80"
            - "8443:443"
        restart: always
        volumes:
            - ./src/public:/var/www/html
              #            - ./etc/nginx/logs/:/var/log/nginx/
              #            - ./etc/nginx/sites-enabled/:/etc/nginx/conf.d/
            - ./etc/nginx/sites-enabled/default.conf:/etc/nginx/sites-enabled/default
        depends_on:
            - php-fpm
            - mysql
            
    php-fpm:
        container_name: php-fpm
        image: php:8.0-fpm
        expose:
            - "9000"
        restart: always
        volumes:
            - ./src/public:/var/www/html
            
    mysql:
        container_name: mysql
        image: mariadb:10.5
        expose:
            - 3306
        restart: always
#        volumes:
#            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            
#    phpmyadmin:
#        container_name: phpmyadmin
#        image: phpmyadmin
#        ports:
#            - "8080:80"
#        restart: always
#        depends_on:
#            - mysql
#        environment:
#            PMA_ARBITRARY: 1
#            PMA_HOST: mysql
            
