version: "3"

services:

  web:
    container_name: web
    image: ifpb/php:7.3-apache-pdo
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306

  adminer:
    container_name: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql

